/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umu.tds.myvideoapp.vista;

import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.EventObject;
import java.util.List;

import pulsador.IEncendidoListener;
import pulsador.Luz;
import tds.video.VideoWeb;
import umu.tds.componente.BuscadorVideos;
import umu.tds.myvideoapp.controlador.ControladorMyVideoApp;
import umu.tds.myvideoapp.dominio.Etiqueta;
import umu.tds.myvideoapp.dominio.ListaVideos;

import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import jdk.nashorn.internal.scripts.JO;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.Icon;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;

/**
 *
 * @author Agustin
 */
public class AppFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form AppFrame
	 */
	public AppFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private JPanel createVistaVideo(JLabel label) {
		JPanel vistaVideo = new JPanel();
		vistaVideo.setMinimumSize(new Dimension(100, 0));
		vistaVideo.setBackground(new Color(51, 51, 51));
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[] { 105, 0, 105, 0 };
		gridBagLayout.rowHeights = new int[] { 40, 0, 0, 0, 0, 0 };
		gridBagLayout.columnWeights = new double[] { 0.0, 1.0, 0.0, Double.MIN_VALUE };
		gridBagLayout.rowWeights = new double[] { 0.0, 0.0, 0.0, 0.0, 1.0, Double.MIN_VALUE };
		vistaVideo.setLayout(gridBagLayout);

		VideoWeb videoWeb = ControladorMyVideoApp.getUnicaInstancia().getVideoWeb();
		GridBagConstraints gbc_videoWeb = new GridBagConstraints();
		gbc_videoWeb.insets = new Insets(0, 0, 5, 5);
		gbc_videoWeb.fill = GridBagConstraints.BOTH;
		gbc_videoWeb.gridx = 1;
		gbc_videoWeb.gridy = 1;
		vistaVideo.add(videoWeb, gbc_videoWeb);

		JPanel panel = new JPanel(new FlowLayout());
		panel.setBackground(new Color(51, 51, 51));
		GridBagConstraints gbc_panel = new GridBagConstraints();
		gbc_panel.insets = new Insets(0, 0, 5, 5);
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.gridx = 1;
		gbc_panel.gridy = 3;
		vistaVideo.add(panel, gbc_panel);

		JButton btnReproducir = new JButton("Reproducir");
		panel.add(btnReproducir);

		JButton btnParar = new JButton("Añadir a");
		btnParar.addMouseListener(new MouseAdapter() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				VentanaListas vl = new VentanaListas(label.getName());
			}
		});
		panel.add(btnParar);

		JButton btnVolver = new JButton("Volver");
		btnVolver.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseReleased(MouseEvent e) {
				rightPanel.remove(vistaVideo);
				ControladorMyVideoApp.getUnicaInstancia().stopVideo();
				rightPanel.add(contentScrollPanel, BorderLayout.CENTER);
				rightPanel.revalidate();
				rightPanel.repaint();
			}
		});
		panel.add(btnVolver);

		JPanel panel_1 = new JPanel();
		panel_1.setBackground(new Color(51, 51, 51));
		GridBagConstraints gbc_panel_1 = new GridBagConstraints();
		gbc_panel_1.gridwidth = 3;
		gbc_panel_1.insets = new Insets(0, 0, 0, 5);
		gbc_panel_1.fill = GridBagConstraints.BOTH;
		gbc_panel_1.gridx = 0;
		gbc_panel_1.gridy = 4;
		vistaVideo.add(panel_1, gbc_panel_1);
		GridBagLayout gbl_panel_1 = new GridBagLayout();
		gbl_panel_1.columnWidths = new int[] { 30, 420, 0 };
		gbl_panel_1.rowHeights = new int[] { 0, 0, 0 };
		gbl_panel_1.columnWeights = new double[] { 0.0, 1.0, Double.MIN_VALUE };
		gbl_panel_1.rowWeights = new double[] { 0.0, 0.0, Double.MIN_VALUE };
		panel_1.setLayout(gbl_panel_1);

		JLabel lblNombre = new JLabel(label.getText());
		lblNombre.setForeground(new Color(255, 255, 255));
		lblNombre.setFont(new Font("Arial", Font.BOLD, 15));
		GridBagConstraints gbc_lblNombre = new GridBagConstraints();
		gbc_lblNombre.insets = new Insets(0, 0, 5, 0);
		gbc_lblNombre.gridx = 1;
		gbc_lblNombre.gridy = 0;
		panel_1.add(lblNombre, gbc_lblNombre);

		JPanel panel_2 = new JPanel();
		panel_2.setBackground(new Color(51, 51, 51));
		GridBagConstraints gbc_panel_2 = new GridBagConstraints();
		gbc_panel_2.fill = GridBagConstraints.BOTH;
		gbc_panel_2.gridx = 1;
		gbc_panel_2.gridy = 1;
		panel_1.add(panel_2, gbc_panel_2);
		GridBagLayout gbl_panel_2 = new GridBagLayout();
		gbl_panel_2.columnWidths = new int[] { 0, 0, 0 };
		gbl_panel_2.rowHeights = new int[] { 0, 0 };
		gbl_panel_2.columnWeights = new double[] { 0.0, 1.0, Double.MIN_VALUE };
		gbl_panel_2.rowWeights = new double[] { 1.0, Double.MIN_VALUE };
		panel_2.setLayout(gbl_panel_2);

		JLabel lblVisitas = new JLabel(String.valueOf(
				ControladorMyVideoApp.getUnicaInstancia().getNumReproducciones(label.getName()) + " reproducciones"));
		lblVisitas.setForeground(new Color(255, 255, 255));
		GridBagConstraints gbc_lblVisitas = new GridBagConstraints();
		gbc_lblVisitas.insets = new Insets(0, 0, 0, 5);
		gbc_lblVisitas.gridx = 0;
		gbc_lblVisitas.gridy = 0;
		panel_2.add(lblVisitas, gbc_lblVisitas);

		JPanel panel_3 = new JPanel();
		panel_3.setBorder(null);
		panel_3.setBackground(new Color(51, 51, 51));
		GridBagConstraints gbc_panel_3 = new GridBagConstraints();
		gbc_panel_3.fill = GridBagConstraints.BOTH;
		gbc_panel_3.gridx = 1;
		gbc_panel_3.gridy = 0;
		panel_2.add(panel_3, gbc_panel_3);

		List<Etiqueta> etiquetas = ControladorMyVideoApp.getUnicaInstancia().getEtiquetasVideo(label.getName());
		for (Etiqueta etiqueta : etiquetas) {
			JLabel lbl = new JLabel(etiqueta.getNombre());
			lbl.setForeground(new Color(0, 153, 204));
			panel_3.add(lbl);
		}

		return vistaVideo;
	}

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		framePanel = new javax.swing.JPanel();
		topPanel = new javax.swing.JPanel();
		logoLabel = new javax.swing.JLabel();
		userIconLabel = new javax.swing.JLabel();
		usernameLabel = new javax.swing.JLabel();
		deployableUserPanel = new javax.swing.JButton();
		leftPanel = new javax.swing.JPanel();
		mostSeenLabel = new javax.swing.JLabel();
		recentLabel = new javax.swing.JLabel();
		newListLabel = new javax.swing.JLabel();
		myListsLabel = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		myListsPanel = new javax.swing.JPanel();
		myListsScrollPanel = new javax.swing.JScrollPane();
		rightPanel = new javax.swing.JPanel();
		contentScrollPanel = new javax.swing.JScrollPane();
		contentPanel = new javax.swing.JPanel();
		searchPanel = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MyVideoApp");
		setMaximumSize(new java.awt.Dimension(4320, 2160));
		setMinimumSize(new java.awt.Dimension(900, 600));
		setName("appFrame"); // NOI18N

		framePanel.setBackground(new java.awt.Color(36, 36, 36));
		framePanel.setMinimumSize(new java.awt.Dimension(900, 600));
		framePanel.setPreferredSize(new java.awt.Dimension(900, 600));

		topPanel.setBackground(new java.awt.Color(42, 42, 42));
		topPanel.setMinimumSize(new java.awt.Dimension(512, 120));
		topPanel.setPreferredSize(new java.awt.Dimension(900, 120));

		// logoLabel.setIcon(new
		// javax.swing.ImageIcon(getClass().getResource("/AppFrame/logo64.png"))); //
		// NOI18N

		// userIconLabel.setIcon(new
		// javax.swing.ImageIcon(getClass().getResource("/AppFrame/userIcon64.png")));
		// // NOI18N

		usernameLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		usernameLabel.setForeground(new java.awt.Color(0, 153, 204));
		usernameLabel.setText("Hola " + ControladorMyVideoApp.getUnicaInstancia().getUsuarioActualName());

		deployableUserPanel.setBorder(null);
		deployableUserPanel.setMaximumSize(new java.awt.Dimension(16, 16));
		deployableUserPanel.setMinimumSize(new java.awt.Dimension(16, 16));
		deployableUserPanel.setPreferredSize(new java.awt.Dimension(16, 16));

		javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
		topPanel.setLayout(topPanelLayout);
		topPanelLayout.setHorizontalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(topPanelLayout.createSequentialGroup().addGap(32, 32, 32)
						.addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(userIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(usernameLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(deployableUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(44, 44, 44)));
		topPanelLayout.setVerticalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(topPanelLayout.createSequentialGroup().addGap(16, 16, 16).addGroup(topPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(userIconLabel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(logoLabel)
						.addGroup(topPanelLayout.createSequentialGroup().addGap(20, 20, 20).addGroup(topPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(deployableUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(usernameLabel))))
						.addGap(16, 16, 16)));

		leftPanel.setBackground(new java.awt.Color(45, 45, 45));

		mostSeenLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		mostSeenLabel.setForeground(new java.awt.Color(0, 153, 204));
		mostSeenLabel.setText("Más vistos");

		recentLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		recentLabel.setForeground(new java.awt.Color(0, 153, 204));
		recentLabel.setText("Recientes");

		newListLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		newListLabel.setForeground(new java.awt.Color(0, 153, 204));
		newListLabel.setText("Nueva Lista");

		myListsLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		myListsLabel.setForeground(new java.awt.Color(0, 153, 204));
		myListsLabel.setText("Mis listas");

		myListsPanel.setBackground(new java.awt.Color(45, 45, 45));
		myListsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

		myListsScrollPanel.setBackground(new java.awt.Color(45, 45, 45));
		myListsScrollPanel.setBorder(null);
		myListsScrollPanel.setMinimumSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout myListsPanelLayout = new javax.swing.GroupLayout(myListsPanel);
		myListsPanelLayout.setHorizontalGroup(myListsPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(myListsPanelLayout.createSequentialGroup()
						.addComponent(myListsScrollPanel, GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
						.addContainerGap()));
		myListsPanelLayout.setVerticalGroup(myListsPanelLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(myListsScrollPanel, GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE));
		myListsPanel.setLayout(myListsPanelLayout);

		table_1 = new JTable();
		table_1.setRowSelectionAllowed(false);
		table_1.setBackground(null);
		table_1.setShowGrid(false);
		table_1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
		
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
					boolean hasFocus, int row, int column) {

				if (value instanceof JButton) {
					JButton label = (JButton) value;
					return label;
				}

				return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
			}
		});
		JButton botonVolverLista = new JButton("Volver a Explorar");
		botonVolverLista.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				rightPanel.removeAll();
				rightPanel.add(searchPanel, BorderLayout.NORTH);
				rightPanel.add(contentScrollPanel, BorderLayout.CENTER);
				rightPanel.revalidate();
				rightPanel.repaint();
				
			}
		});
		
		// Inicializa la tabla de videos para las listas
		listaVideosScrollPanel = new JScrollPane();
		listaVideosScrollPanel.setBackground(new Color(50, 50, 50));
		listaVideosScrollPanel.setBorder(null);
		listaVideosScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		
		listaVideosPanel = new JPanel(new BorderLayout(0, 0));
		listaVideosPanel.setBackground(new Color(50, 50, 50));
		listaVideosPanel.setForeground(new java.awt.Color(0, 153, 204));
		//listaVideosScrollPanel.setViewportView(listaVideosPanel);
		
		tableListaVideos = new JTable();
		//listaVideosPanel.add(tableListaVideos, BorderLayout.CENTER);
		listaVideosScrollPanel.setViewportView(tableListaVideos);
		
		//listaVideosPanel.add(new JLabel("Esto no va"), BorderLayout.CENTER);
		
		listaVideoBotonesPanel = new JPanel();
		listaVideoBotonesPanel.setBackground(new Color(50, 50, 50));
		listaVideoBotonesPanel.add(botonVolverLista);
		
		
		// Crea la tabla de listas
		createTableListas();

		// Boton crear nueva lista
		addButton = new JButton("");
		addButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String nombreLista = JOptionPane.showInputDialog(framePanel, "¿Como quieres llamar a la nueva lista?",
						"Nueva Lista", JOptionPane.QUESTION_MESSAGE);
				if (nombreLista != null) {
					ControladorMyVideoApp.getUnicaInstancia().registrarListaVideos(nombreLista);
					createTableListas();

				}
			}
		});
		addButton.setBorderPainted(false);
		addButton.setBackground(null);
		addButton.setBorderPainted(false);
		addButton.setIcon(new ImageIcon(AppFrame.class.getResource("/sources/add.png")));

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
		leftPanelLayout.setHorizontalGroup(leftPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(leftPanelLayout.createSequentialGroup().addGroup(leftPanelLayout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(leftPanelLayout.createSequentialGroup().addGap(32).addGroup(leftPanelLayout
								.createParallelGroup(Alignment.LEADING).addComponent(recentLabel)
								.addComponent(mostSeenLabel)
								.addComponent(jSeparator1, GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
								.addComponent(myListsLabel)
								.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGroup(leftPanelLayout.createSequentialGroup().addComponent(newListLabel).addGap(14)
										.addComponent(addButton, GroupLayout.PREFERRED_SIZE, 28,
												GroupLayout.PREFERRED_SIZE))
								.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
								.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE))
								.addGap(17))
						.addGroup(leftPanelLayout.createSequentialGroup().addGap(64).addComponent(myListsPanel,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addGap(32)));
		leftPanelLayout.setVerticalGroup(leftPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(leftPanelLayout.createSequentialGroup().addGap(32).addComponent(mostSeenLabel).addGap(4)
						.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addGap(12).addComponent(recentLabel).addGap(4)
						.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(leftPanelLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(leftPanelLayout.createSequentialGroup().addGap(12).addComponent(newListLabel))
								.addGroup(leftPanelLayout.createSequentialGroup().addGap(7).addComponent(addButton,
										GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
						.addGap(4).addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addGap(12).addComponent(myListsLabel).addGap(4)
						.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(myListsPanel, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE).addGap(32)));
		leftPanel.setLayout(leftPanelLayout);

		rightPanel.setBackground(new java.awt.Color(50, 50, 50));

		contentScrollPanel.setBackground(new java.awt.Color(50, 50, 50));
		contentScrollPanel.setBorder(null);
		contentScrollPanel.setForeground(new java.awt.Color(0, 153, 204));
		contentScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		contentPanel.setBackground(new java.awt.Color(50, 50, 50));
		contentPanel.setForeground(new java.awt.Color(0, 153, 204));
		contentScrollPanel.setViewportView(contentPanel);

		generateTableVideos();
		contentPanel.add(table, BorderLayout.CENTER);

		searchPanel.setBackground(new java.awt.Color(50, 50, 50));
		GridBagLayout gbl_searchPanel = new GridBagLayout();
		gbl_searchPanel.columnWidths = new int[] { 30, 232, 232, 0, 0 };
		gbl_searchPanel.rowHeights = new int[] { 30, 24, 10, 27, 0 };
		gbl_searchPanel.columnWeights = new double[] { 0.0, 0.0, 1.0, 1.0, Double.MIN_VALUE };
		gbl_searchPanel.rowWeights = new double[] { 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE };
		searchPanel.setLayout(gbl_searchPanel);
		searchTextField = new javax.swing.JTextField();

		searchTextField.setBackground(new java.awt.Color(50, 50, 50));
		searchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		searchTextField.setForeground(new java.awt.Color(0, 153, 204));
		searchTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		searchTextField.setText("Search...");
		searchTextField.setBorder(null);
		searchTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchTextFieldActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_searchTextField = new GridBagConstraints();
		gbc_searchTextField.gridwidth = 2;
		gbc_searchTextField.fill = GridBagConstraints.BOTH;
		gbc_searchTextField.insets = new Insets(0, 0, 5, 5);
		gbc_searchTextField.gridx = 1;
		gbc_searchTextField.gridy = 1;
		searchPanel.add(searchTextField, gbc_searchTextField);

		luz = new Luz();
		bv = new BuscadorVideos();
		bv.addVideosListener(ControladorMyVideoApp.getUnicaInstancia());
		luz.addEncendidoListener(bv);
		luz.addEncendidoListener(new IEncendidoListener() {

			@Override
			public void enteradoCambioEncendido(EventObject arg0) {
				contentPanel.remove(table);
				generateTableVideos();
				contentPanel.add(table, BorderLayout.CENTER);
				rightPanel.revalidate();
				rightPanel.repaint();
			}
		});

		bv = new BuscadorVideos();
		GridBagConstraints gbc_luz = new GridBagConstraints();
		gbc_luz.gridheight = 3;
		gbc_luz.gridx = 3;
		gbc_luz.gridy = 1;
		searchPanel.add(luz, gbc_luz);
		jSeparator5 = new javax.swing.JSeparator();
		GridBagConstraints gbc_jSeparator5 = new GridBagConstraints();
		gbc_jSeparator5.gridwidth = 2;
		gbc_jSeparator5.fill = GridBagConstraints.BOTH;
		gbc_jSeparator5.insets = new Insets(0, 0, 5, 5);
		gbc_jSeparator5.gridx = 1;
		gbc_jSeparator5.gridy = 2;
		searchPanel.add(jSeparator5, gbc_jSeparator5);
		tagComboBox = new javax.swing.JComboBox<>();

		tagComboBox.setBackground(new java.awt.Color(50, 50, 50));
		tagComboBox.setForeground(new java.awt.Color(0, 153, 204));
		tagComboBox.setMaximumRowCount(64);
		tagComboBox.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin filtro", "Item 2", "Item 3", "Item 4" }));
		tagComboBox.setBorder(null);
		GridBagConstraints gbc_tagComboBox = new GridBagConstraints();
		gbc_tagComboBox.anchor = GridBagConstraints.NORTHWEST;
		gbc_tagComboBox.insets = new Insets(0, 0, 0, 5);
		gbc_tagComboBox.gridx = 1;
		gbc_tagComboBox.gridy = 3;
		searchPanel.add(tagComboBox, gbc_tagComboBox);

		javax.swing.GroupLayout framePanelLayout = new javax.swing.GroupLayout(framePanel);
		framePanel.setLayout(framePanelLayout);
		framePanelLayout
				.setHorizontalGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(framePanelLayout.createSequentialGroup()
								.addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(8, 8, 8).addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		framePanelLayout.setVerticalGroup(framePanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePanelLayout.createSequentialGroup()
						.addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(8, 8, 8)
						.addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		rightPanel.setLayout(new BorderLayout(0, 0));
		rightPanel.add(contentScrollPanel, BorderLayout.CENTER);
		rightPanel.add(searchPanel, BorderLayout.NORTH);

		btnEtiquetas = new JButton("Etiquetas");
		btnEtiquetas.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseReleased(MouseEvent e) {
				VentanaEtiquetas ventanaEtiquetas = new VentanaEtiquetas();
			}
		});
		btnEtiquetas.setForeground(new Color(0, 0, 0));
		JPanel panelBtn = new JPanel(new FlowLayout());
		panelBtn.setBackground(new Color(51, 51, 51));
		panelBtn.add(btnEtiquetas);
		GridBagConstraints gbc_panelBtn = new GridBagConstraints();
		gbc_panelBtn.insets = new Insets(0, 0, 0, 5);
		gbc_panelBtn.gridx = 2;
		gbc_panelBtn.gridy = 3;
		searchPanel.add(panelBtn, gbc_panelBtn);

		btnRefrescar = new JButton("Refrescar");
		btnRefrescar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				contentPanel.remove(table);
				generateTableVideos();
				contentPanel.add(table, BorderLayout.CENTER);
				rightPanel.revalidate();
				rightPanel.repaint();
			}
		});
		panelBtn.add(btnRefrescar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(framePanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(framePanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void createTableListas() {
		table_1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// VistaVideo vistaVideo = new VistaVideo();
				int column = table_1.getColumnModel().getColumnIndexAtX(e.getX());
				int row = e.getY() / table_1.getRowHeight();

				if (row < table_1.getRowCount() && row >= 0 && column < table_1.getColumnCount() && column >= 0) {
					Object value = table_1.getValueAt(row, column);
					if (value instanceof JButton) {
						System.out.println("click lista");
						JButton button = (JButton) value;
						rightPanel.removeAll();
						/*
						rightPanel.remove(contentScrollPanel);
						rightPanel.remove(searchPanel);
						*/
						createVistaListaVideos(button.getName());
						rightPanel.add(new JLabel(button.getName()), BorderLayout.NORTH);
						rightPanel.add(listaVideosScrollPanel, BorderLayout.CENTER);
						rightPanel.add(listaVideoBotonesPanel, BorderLayout.SOUTH);
						rightPanel.revalidate();
						rightPanel.repaint();
						//rightPanel.add(contentScrollPanel, BorderLayout.CENTER);
						//rightPanel.add(searchPanel, BorderLayout.NORTH);
					}
				}
			}

		});
		Object[] data = ControladorMyVideoApp.getUnicaInstancia().getListasUsuario();
		Object[][] model_data = new Object[data.length][2];
		for (int i = 0; i < data.length; i++) {
			ListaVideos lv = (ListaVideos) data[i];
			model_data[i][0] = lv.getNombreLista();
			JButton listButton = new JButton("Boton");
			listButton.setName(lv.getNombreLista());
			model_data[i][1] = listButton;
		}
		DefaultTableModel model = new DefaultTableModel(model_data, new Object[] { "", "" }) {
			private static final long serialVersionUID = 1L;

			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		table_1.setModel(model);
		table_1.setSelectionForeground(null);
		table_1.setSelectionBackground(null);
		table_1.setCellSelectionEnabled(false);
		myListsScrollPanel.setViewportView(table_1);
		myListsScrollPanel.getViewport().setBackground(null);
	}

	private void createVistaListaVideos(String nombreLista) {
		
		
		tableListaVideos = new JTable();
		tableListaVideos.setRowSelectionAllowed(false);
		tableListaVideos.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// VistaVideo vistaVideo = new VistaVideo();
				int column = tableListaVideos.getColumnModel().getColumnIndexAtX(e.getX());
				int row = e.getY() / tableListaVideos.getRowHeight();

				if (row < tableListaVideos.getRowCount() && row >= 0 && column < tableListaVideos.getColumnCount() && column >= 0) {
					Object value = tableListaVideos.getValueAt(row, column);
					if (value instanceof JLabel) {

						JLabel label = (JLabel) value;
						JPanel vistaVideo = createVistaVideo(label);
						rightPanel.remove(listaVideosScrollPanel);
						rightPanel.add(vistaVideo, BorderLayout.CENTER);
						rightPanel.revalidate();
						rightPanel.repaint();
						ControladorMyVideoApp.getUnicaInstancia().verVideo(label.getName());
					}
				}
			}
		});
		tableListaVideos.setShowGrid(false);
		tableListaVideos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public Component getTableCellRendererComponent(JTable tableListaVideos, Object value, boolean isSelected,
					boolean hasFocus, int row, int column) {

				if (value instanceof JLabel) {
					JLabel label = (JLabel) value;
					return label;
				}

				return super.getTableCellRendererComponent(tableListaVideos, value, isSelected, hasFocus, row, column);
			}
		});
		Object tab[][] = ControladorMyVideoApp.getUnicaInstancia().videosToArray(nombreLista);
		DefaultTableModel model = new DefaultTableModel(tab, new Object[] { "", "", "" }) {
			private static final long serialVersionUID = 1L;

			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		//tableListaVideos.setBackground(null);
		tableListaVideos.setModel(model);
	    listaVideosPanel.setLayout(new BorderLayout(0, 0));
		tableListaVideos.setRowHeight(120);
		tableListaVideos.setRowMargin(5);
	}

	private void generateTableVideos() {
		table = new JTable();
		table.setRowSelectionAllowed(false);
		table.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// VistaVideo vistaVideo = new VistaVideo();
				int column = table.getColumnModel().getColumnIndexAtX(e.getX());
				int row = e.getY() / table.getRowHeight();

				if (row < table.getRowCount() && row >= 0 && column < table.getColumnCount() && column >= 0) {
					Object value = table.getValueAt(row, column);
					if (value instanceof JLabel) {

						JLabel label = (JLabel) value;
						JPanel vistaVideo = createVistaVideo(label);
						rightPanel.remove(contentScrollPanel);
						rightPanel.add(vistaVideo, BorderLayout.CENTER);
						rightPanel.revalidate();
						rightPanel.repaint();
						ControladorMyVideoApp.getUnicaInstancia().verVideo(label.getName());
					}
				}
			}
		});
		table.setShowGrid(false);
		table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
					boolean hasFocus, int row, int column) {

				if (value instanceof JLabel) {
					JLabel label = (JLabel) value;
					return label;
				}

				return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
			}
		});
		Object tab[][] = ControladorMyVideoApp.getUnicaInstancia().videosToArray();
		DefaultTableModel model = new DefaultTableModel(tab, new Object[] { "", "", "" }) {
			private static final long serialVersionUID = 1L;

			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		table.setBackground(null);
		table.setModel(model);
		contentPanel.setLayout(new BorderLayout(0, 0));
		table.setRowHeight(120);
		table.setRowMargin(5);
	}

	private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_searchTextFieldActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		System.out.println("Entra en AppFrame");
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AppFrame().setVisible(true);
			}
		});
	}

	private javax.swing.JPanel contentPanel;
	private javax.swing.JScrollPane contentScrollPanel;
	private javax.swing.JButton deployableUserPanel;
	private javax.swing.JPanel framePanel;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JLabel logoLabel;
	private javax.swing.JLabel mostSeenLabel;
	private javax.swing.JLabel myListsLabel;
	private javax.swing.JPanel myListsPanel;
	private javax.swing.JScrollPane myListsScrollPanel;
	private javax.swing.JLabel newListLabel;
	private javax.swing.JLabel recentLabel;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JPanel searchPanel;
	private javax.swing.JTextField searchTextField;
	private javax.swing.JComboBox<String> tagComboBox;
	private javax.swing.JPanel topPanel;
	private javax.swing.JLabel userIconLabel;
	private javax.swing.JLabel usernameLabel;
	private Luz luz;
	private BuscadorVideos bv;
	private JTable table;
	private JList<JCheckBox> list;
	private JButton btnEtiquetas;
	private JButton btnRefrescar;
	private JButton addButton;
	private JTable table_1;
	private JPanel listaVideosPanel;
	private JPanel listaVideoBotonesPanel;
	private JTable tableListaVideos;
	private JScrollPane listaVideosScrollPanel;
}
