/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umu.tds.myvideoapp.vista;

import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.EventObject;
import java.util.List;

import pulsador.IEncendidoListener;
import pulsador.Luz;
import tds.video.VideoWeb;
import umu.tds.componente.BuscadorVideos;
import umu.tds.myvideoapp.controlador.ControladorMyVideoApp;
import umu.tds.myvideoapp.dominio.Etiqueta;
import umu.tds.myvideoapp.dominio.ListaVideos;

import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import jdk.nashorn.internal.scripts.JO;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.Icon;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;

/**
 *
 * @author Agustin
 */
public class AppFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form AppFrame
	 */
	public AppFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		framePanel = new javax.swing.JPanel();
		topPanel = new javax.swing.JPanel();
		logoLabel = new javax.swing.JLabel();
		userIconLabel = new javax.swing.JLabel();
		usernameLabel = new javax.swing.JLabel();
		deployableUserPanel = new javax.swing.JButton();
		leftPanel = new javax.swing.JPanel();
		mostSeenLabel = new javax.swing.JLabel();
		recentLabel = new javax.swing.JLabel();
		newListLabel = new javax.swing.JLabel();
		myListsLabel = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		myListsPanel = new javax.swing.JPanel();
		myListsScrollPanel = new javax.swing.JScrollPane();
		rightPanel = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MyVideoApp");
		setMaximumSize(new java.awt.Dimension(4320, 2160));
		setMinimumSize(new java.awt.Dimension(900, 600));
		setName("appFrame"); // NOI18N

		framePanel.setBackground(new java.awt.Color(36, 36, 36));
		framePanel.setMinimumSize(new java.awt.Dimension(900, 600));
		framePanel.setPreferredSize(new java.awt.Dimension(900, 600));

		topPanel.setBackground(new java.awt.Color(42, 42, 42));
		topPanel.setMinimumSize(new java.awt.Dimension(512, 120));
		topPanel.setPreferredSize(new java.awt.Dimension(900, 120));

		// logoLabel.setIcon(new
		// javax.swing.ImageIcon(getClass().getResource("/AppFrame/logo64.png"))); //
		// NOI18N

		// userIconLabel.setIcon(new
		// javax.swing.ImageIcon(getClass().getResource("/AppFrame/userIcon64.png")));
		// // NOI18N

		usernameLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		usernameLabel.setForeground(new java.awt.Color(0, 153, 204));
		usernameLabel.setText("Hola " + ControladorMyVideoApp.getUnicaInstancia().getUsuarioActualName());

		deployableUserPanel.setBorder(null);
		deployableUserPanel.setMaximumSize(new java.awt.Dimension(16, 16));
		deployableUserPanel.setMinimumSize(new java.awt.Dimension(16, 16));
		deployableUserPanel.setPreferredSize(new java.awt.Dimension(16, 16));

		javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
		topPanel.setLayout(topPanelLayout);
		topPanelLayout.setHorizontalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(topPanelLayout.createSequentialGroup().addGap(32, 32, 32)
						.addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(userIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(usernameLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(deployableUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(44, 44, 44)));
		topPanelLayout.setVerticalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(topPanelLayout.createSequentialGroup().addGap(16, 16, 16).addGroup(topPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(userIconLabel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(logoLabel)
						.addGroup(topPanelLayout.createSequentialGroup().addGap(20, 20, 20).addGroup(topPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(deployableUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(usernameLabel))))
						.addGap(16, 16, 16)));

		leftPanel.setBackground(new java.awt.Color(45, 45, 45));

		mostSeenLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		mostSeenLabel.setForeground(new java.awt.Color(0, 153, 204));
		mostSeenLabel.setText("Más vistos");

		recentLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		recentLabel.setForeground(new java.awt.Color(0, 153, 204));
		recentLabel.setText("Recientes");

		newListLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		newListLabel.setForeground(new java.awt.Color(0, 153, 204));
		newListLabel.setText("Nueva Lista");

		myListsLabel.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
		myListsLabel.setForeground(new java.awt.Color(0, 153, 204));
		myListsLabel.setText("Mis listas");

		myListsPanel.setBackground(new java.awt.Color(45, 45, 45));
		myListsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

		myListsScrollPanel.setBackground(new java.awt.Color(45, 45, 45));
		myListsScrollPanel.setBorder(null);
		myListsScrollPanel.setMinimumSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout myListsPanelLayout = new javax.swing.GroupLayout(myListsPanel);
		myListsPanelLayout.setHorizontalGroup(myListsPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(myListsPanelLayout.createSequentialGroup()
						.addComponent(myListsScrollPanel, GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
						.addContainerGap()));
		myListsPanelLayout.setVerticalGroup(myListsPanelLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(myListsScrollPanel, GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE));
		myListsPanel.setLayout(myListsPanelLayout);

		table_1 = new JTable();
		table_1.setRowSelectionAllowed(false);
		table_1.setBackground(null);
		table_1.setShowGrid(false);
		table_1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
		
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
					boolean hasFocus, int row, int column) {

				if (value instanceof JButton) {
					JButton label = (JButton) value;
					return label;
				}

				return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
			}
		});
		
		
		// Crea la tabla de listas
		createTableListas();

		// Boton crear nueva lista
		addButton = new JButton("");
		addButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String nombreLista = JOptionPane.showInputDialog(framePanel, "¿Como quieres llamar a la nueva lista?",
						"Nueva Lista", JOptionPane.QUESTION_MESSAGE);
				if (nombreLista != null) {
					ControladorMyVideoApp.getUnicaInstancia().registrarListaVideos(nombreLista);
					createTableListas();

				}
			}
		});
		addButton.setBorderPainted(false);
		addButton.setBackground(null);
		addButton.setBorderPainted(false);
		addButton.setIcon(new ImageIcon(AppFrame.class.getResource("/sources/add.png")));

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
		leftPanelLayout.setHorizontalGroup(leftPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(leftPanelLayout.createSequentialGroup().addGroup(leftPanelLayout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(leftPanelLayout.createSequentialGroup().addGap(32).addGroup(leftPanelLayout
								.createParallelGroup(Alignment.LEADING).addComponent(recentLabel)
								.addComponent(mostSeenLabel)
								.addComponent(jSeparator1, GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
								.addComponent(myListsLabel)
								.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGroup(leftPanelLayout.createSequentialGroup().addComponent(newListLabel).addGap(14)
										.addComponent(addButton, GroupLayout.PREFERRED_SIZE, 28,
												GroupLayout.PREFERRED_SIZE))
								.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
								.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 219, GroupLayout.PREFERRED_SIZE))
								.addGap(17))
						.addGroup(leftPanelLayout.createSequentialGroup().addGap(64).addComponent(myListsPanel,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addGap(32)));
		leftPanelLayout.setVerticalGroup(leftPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(leftPanelLayout.createSequentialGroup().addGap(32).addComponent(mostSeenLabel).addGap(4)
						.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addGap(12).addComponent(recentLabel).addGap(4)
						.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(leftPanelLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(leftPanelLayout.createSequentialGroup().addGap(12).addComponent(newListLabel))
								.addGroup(leftPanelLayout.createSequentialGroup().addGap(7).addComponent(addButton,
										GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
						.addGap(4).addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addGap(12).addComponent(myListsLabel).addGap(4)
						.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(myListsPanel, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE).addGap(32)));
		leftPanel.setLayout(leftPanelLayout);


		
		javax.swing.GroupLayout framePanelLayout = new javax.swing.GroupLayout(framePanel);
		framePanel.setLayout(framePanelLayout);
		framePanelLayout
				.setHorizontalGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(framePanelLayout.createSequentialGroup()
								.addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(8, 8, 8).addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		framePanelLayout.setVerticalGroup(framePanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePanelLayout.createSequentialGroup()
						.addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(8, 8, 8)
						.addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		
		rightPanel.setBackground(new java.awt.Color(50, 50, 50));
		rightPanel.setLayout(new BorderLayout(0, 0));
		rightPanel.add(new JPanelTablaVideos());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(framePanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(framePanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void createTableListas() {
		table_1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// VistaVideo vistaVideo = new VistaVideo();
				int column = table_1.getColumnModel().getColumnIndexAtX(e.getX());
				int row = e.getY() / table_1.getRowHeight();

				if (row < table_1.getRowCount() && row >= 0 && column < table_1.getColumnCount() && column >= 0) {
					Object value = table_1.getValueAt(row, column);
					if (value instanceof JButton) {
						System.out.println("click lista");
						JButton button = (JButton) value;
						rightPanel.removeAll();

						rightPanel.add(new JPanelTablaVideosLista(button.getName(), thisFrame));
						
						rightPanel.revalidate();
						rightPanel.repaint();
					}
				}
			}

		});
		Object[] data = ControladorMyVideoApp.getUnicaInstancia().getListasUsuario();
		Object[][] model_data = new Object[data.length][2];
		for (int i = 0; i < data.length; i++) {
			ListaVideos lv = (ListaVideos) data[i];
			model_data[i][0] = lv.getNombreLista();
			JButton listButton = new JButton("Boton");
			listButton.setName(lv.getNombreLista());
			model_data[i][1] = listButton;
		}
		DefaultTableModel model = new DefaultTableModel(model_data, new Object[] { "", "" }) {
			private static final long serialVersionUID = 1L;

			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		table_1.setModel(model);
		table_1.setSelectionForeground(null);
		table_1.setSelectionBackground(null);
		table_1.setCellSelectionEnabled(false);
		myListsScrollPanel.setViewportView(table_1);
		myListsScrollPanel.getViewport().setBackground(null);
	}

	public void volverAExplorar() {
		rightPanel.removeAll();
		rightPanel.add(new JPanelTablaVideos());
		revalidate();
		repaint();
	}
	
	private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_searchTextFieldActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		System.out.println("Entra en AppFrame");
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AppFrame().setVisible(true);
			}
		});
	}

	private AppFrame thisFrame = this;
	
	private javax.swing.JButton deployableUserPanel;
	private javax.swing.JPanel framePanel;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JLabel logoLabel;
	private javax.swing.JLabel mostSeenLabel;
	private javax.swing.JLabel myListsLabel;
	private javax.swing.JPanel myListsPanel;
	private javax.swing.JScrollPane myListsScrollPanel;
	private javax.swing.JLabel newListLabel;
	private javax.swing.JLabel recentLabel;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JPanel topPanel;
	private javax.swing.JLabel userIconLabel;
	private javax.swing.JLabel usernameLabel;
	private JButton addButton;
	private JTable table_1;
}
